'use strict';

const Groq = require('groq-sdk');
const config = require('../config');
const logger = require('../utils/logger');
const { withRetry, withTimeout } = require('../utils/helpers');

/**
 * LLM Service — Groq
 *
 * Responsible for generating answers from retrieved context.
 * Uses a strict system prompt to ensure answers are grounded in documents.
 */

const groqClient = new Groq({
  apiKey: config.groq.apiKey,
});

/**
 * System prompt — enforces grounded, document-only answers.
 */
const SYSTEM_PROMPT = `
You are a smart, human-like AI assistant.

GOAL:
Act like a real assistant having a natural conversation.

RULES:

1. Greeting Handling:
- Only respond with greeting if user clearly greets (hi, hello).
- Do NOT repeat greeting again in conversation.

2. Conversation Behavior:
- Understand the intent, not just keywords.
- If user asks a question like "how are you", respond naturally:
  "I'm doing well! How can I help you today?"

3. Document Answering:
- If question relates to document → answer from context.
- Keep answer clear and concise.

4. If not found:
- Respond naturally:
  "I couldn’t find that in the document, but I can help if you give more details."

5. Voice Optimization (IMPORTANT):
- Keep answers SHORT (2–4 lines max)
- Avoid long paragraphs
- Sound natural when spoken

6. Tone:
- Friendly, human-like
- Not robotic
- Not repetitive

7. NEVER:
- Repeat greetings unnecessarily
- Dump large raw content
- Sound like a system

GOAL:
Behave like a real human assistant in conversation, especially for voice interaction.
`;

/**
 * Builds the user message combining question and retrieved context.
 *
 * @param {string} question
 * @param {string} context
 * @returns {string}
 */
function buildUserMessage(question, context) {
  return `DOCUMENT CONTEXT:
──────────────────────────────
${context}
──────────────────────────────

USER QUESTION: ${question}

Please answer based ONLY on the document context above.`;
}

/**
 * Generates an answer using Groq LLM with provided context.
 *
 * @param {string} question - user question
 * @param {string} context - retrieved context from Pinecone
 * @returns {Promise<string>} - generated answer text
 */
async function generateAnswer(question, context) {
  logger.info(`[LLMService] Sending request to Groq (model: ${config.groq.model})`);

  const messages = [
    { role: 'system', content: SYSTEM_PROMPT },
    { role: 'user', content: buildUserMessage(question, context) },
  ];

  async function callGroq(messagesPayload) {
    logger.info('[LLM] Trying Groq...');
    for (let i = 0; i < 2; i++) {
      try {
        return await groqClient.chat.completions.create({
          model: config.groq.model,
          messages: messagesPayload,
          temperature: 0.1,
          max_tokens: 1024,
          top_p: 0.9,
          stream: false,
        });
      } catch (err) {
        if (i < 1) {
          logger.info("[LLM] Groq failed, retrying...");
          await new Promise(r => setTimeout(r, 1000));
        }
      }
    }
    throw new Error("Groq failed after retries");
  }

  const completion = await callGroq(messages);

  const answer = completion.choices?.[0]?.message?.content?.trim();

  if (!answer) {
    throw new Error('[LLMService] Groq returned empty response');
  }

  logger.info('[LLMService] ✅ Final response generated by Groq');
  return answer;
}

module.exports = { generateAnswer };
